name: "Setup nspire Tools"
description: "Setup Luna, Sol and nspire-merge"

runs:
  using: "composite"
  steps:
    - name: "Set environment variables"
      shell: bash
      run: |
        echo "TOOLS_BIN_FOLDER=$HOME/tools" >> $GITHUB_ENV
        echo "TOOLS_TEMP_FOLDER=$HOME/nspire-tools" >> $GITHUB_ENV
  
    - name: "Create folders"
      shell: bash
      run: |
        mkdir -vp "$TOOLS_BIN_FOLDER"
        mkdir -vp "$TOOLS_TEMP_FOLDER"
        echo "$TOOLS_BIN_FOLDER" >> $GITHUB_PATH

    - name: "Install nspire-merge"
      shell: bash
      run: |
        git clone "https://github.com/alexcoder04/nspire-merge" "$TOOLS_TEMP_FOLDER/nspire-merge"
        cd "$TOOLS_TEMP_FOLDER/nspire-merge"
        install -Dm755 nspire-merge "$TOOLS_BIN_FOLDER/nspire-merge"
        pip install Pillow

    - name: "Setup Go environment"
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: "Install Sol"
      shell: bash
      run: |
        git clone "https://github.com/alexcoder04/sol-tools" "$TOOLS_TEMP_FOLDER/sol-tools"
        cd "$TOOLS_TEMP_FOLDER/sol-tools"
        make linux
        install -Dm755 build/sol "$TOOLS_BIN_FOLDER/sol"

    - name: "Install Luna"
      shell: bash
      run: |
        git clone "https://github.com/ndless-nspire/Luna" "$TOOLS_TEMP_FOLDER/Luna"
        cd "$TOOLS_TEMP_FOLDER/Luna"
        make
        install -Dm755 luna "$TOOLS_BIN_FOLDER/luna"
        
    - name: "Clean up"
      shell: bash
      run: |
        rm -rf "$TOOLS_TEMP_FOLDER"
